import json
import re
import duckdb
import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "llama3.2:3b"

ALLOWED_STANCES = {
    "CLAIM",
    "COUNTER_CLAIM",
    "NEUTRAL_OR_OTHER"
}

ALLOWED_MUTATIONS = {
    "CERTAINTY_INFLATION",
    "QUALIFIER_LOSS",
    "POPULATION_EXPANSION",
    "OUTCOME_EXPANSION",
    "CAUSAL_INFLATION",
    "MAGNITUDE_EXAGGERATION",
    "RISK_AMPLIFICATION",
    "BENEFIT_DELETION",
    "RECOMMENDATION_LEAP",
    "NONE"
}

ALLOWED_BEHAVIORS = {
    "NONE",
    "EXPECTATION",
    "TRY",
    "BUY",
    "REQUEST",
    "RECOMMEND",
    "STOP",
    "AVOID",
    "SWITCH",
    "DELAY"
}

# Explicit behavior cues.
# If these are absent, we do NOT allow the model to infer behavior.
BEHAVIOR_PATTERNS = {
    "TRY": [
        r"\bi(?:'m| am) going to try\b",
        r"\bi(?:'ll| will) try\b"
    ],
    "BUY": [
        r"\bi(?:'m| am) going to buy\b",
        r"\bi(?:'ll| will) buy\b"
    ],
    "REQUEST": [
        r"\bi(?:'ll| will) ask\b",
        r"\bask my doctor\b",
        r"\brequest\b"
    ],
    "RECOMMEND": [
        r"\bdon'?t get\b",
        r"\bdo not get\b",
        r"\bdon'?t take\b",
        r"\bdo not take\b",
        r"\byou should avoid\b"
    ],
    "STOP": [
        r"\bstop taking\b",
        r"\bno more shots\b",
        r"\bno more vaccines\b"
    ],
    "AVOID": [
        r"\bi won'?t get\b",
        r"\bi will not get\b",
        r"\bi(?:'m| am) not getting\b",
        r"\bnever getting\b",
        r"\bi refuse\b",
        r"\bi(?:'m| am) avoiding\b"
    ],
    "SWITCH": [
        r"\bi(?:'m| am) switching\b",
        r"\bi switched\b"
    ],
    "DELAY": [
        r"\bi(?:'m| am) delaying\b",
        r"\bi(?:'ll| will) wait\b",
        r"\bpostpone\b"
    ]
}

def deterministic_behavior(text):
    text = text.lower()

    for label, patterns in BEHAVIOR_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, text):
                return label

    return "NONE"


def validate_analysis(analysis, body):
    body_lower = body.lower()

    # Fill missing fields
    analysis.setdefault("stance", "NEUTRAL_OR_OTHER")
    analysis.setdefault("normalized_claim", "")
    analysis.setdefault("mutation_features", ["NONE"])
    analysis.setdefault("behavior", "NONE")
    analysis.setdefault(
        "explanation",
        "Classification generated by local semantic model."
    )

    # Validate stance
    if analysis["stance"] not in ALLOWED_STANCES:
        analysis["stance"] = "NEUTRAL_OR_OTHER"

    # Strong deterministic counter-claim correction
    counter_phrases = [
        "turbo cancer doesn't exist",
        "turbo cancer does not exist"
    ]

    if any(p in body_lower for p in counter_phrases):
        analysis["stance"] = "COUNTER_CLAIM"

    # Validate mutation list
    mutations = analysis["mutation_features"]

    if not isinstance(mutations, list):
        mutations = ["NONE"]

    mutations = [
        m for m in mutations
        if m in ALLOWED_MUTATIONS
    ]

    if not mutations:
        mutations = ["NONE"]

    # Counter-claims / unrelated posts do not inherit
    # mutation labels from the canonical claim.
    if analysis["stance"] != "CLAIM":
        mutations = ["NONE"]

    analysis["mutation_features"] = mutations

    # Behavior is validated deterministically.
    # A health claim alone is NOT behavioral intention.
    analysis["behavior"] = deterministic_behavior(body)

    return analysis


rows = duckdb.sql("""
SELECT
    body,
    COUNT(*) AS observed_count,
    MIN(created_at) AS first_seen
FROM read_parquet('tweets-000000.parquet')
WHERE lang = 'en'
  AND (
        lower(body) LIKE '%covid vaccine%'
        OR lower(body) LIKE '%mrna vaccine%'
        OR lower(body) LIKE '%pfizer%'
      )
  AND (
        lower(body) LIKE '%cancer%'
        OR lower(body) LIKE '%turbo cancer%'
      )
GROUP BY body
ORDER BY observed_count DESC
""").fetchall()

results = []

for i, (body, observed_count, first_seen) in enumerate(rows, 1):

    prompt = f"""
You are a semantic extraction system for public-health research.

Canonical narrative:
"COVID-19 mRNA vaccines cause turbo cancer."

Analyze ONLY what this post says.
Do NOT judge whether the medical statement is scientifically true.

POST:
{body}

Return JSON only with:

{{
  "stance": "CLAIM | COUNTER_CLAIM | NEUTRAL_OR_OTHER",
  "normalized_claim": "one concise neutral sentence preserving the main health claim",
  "mutation_features": [],
  "behavior": "NONE",
  "explanation": "one short sentence"
}}

Allowed mutation features:
CERTAINTY_INFLATION
QUALIFIER_LOSS
POPULATION_EXPANSION
OUTCOME_EXPANSION
CAUSAL_INFLATION
MAGNITUDE_EXAGGERATION
RISK_AMPLIFICATION
BENEFIT_DELETION
RECOMMENDATION_LEAP
NONE

Rules:
- CLAIM = asserts or strengthens the narrative.
- COUNTER_CLAIM = rejects the narrative.
- NEUTRAL_OR_OTHER = neither.
- If COUNTER_CLAIM, mutation_features must be ["NONE"].
- Do not infer behavior.
- Preserve cancer-related wording.
- Do not invent information.
"""

    response = requests.post(
        OLLAMA_URL,
        json={
            "model": MODEL,
            "prompt": prompt,
            "stream": False,
            "format": "json",
            "options": {
                "temperature": 0
            }
        },
        timeout=180
    )

    response.raise_for_status()

    try:
        analysis = json.loads(response.json()["response"])
    except Exception:
        analysis = {}

    analysis = validate_analysis(analysis, body)

    result = {
        "variant_number": i,
        "observed_count": observed_count,
        "first_seen": str(first_seen),
        "original_post": body,
        **analysis
    }

    results.append(result)

    print(f"\n--- VARIANT {i} ---")
    print("Observed:", observed_count)
    print("Stance:", result["stance"])
    print("Normalized:", result["normalized_claim"])
    print("Mutation:", result["mutation_features"])
    print("Behavior:", result["behavior"])
    print("Why:", result["explanation"])

with open("llm_analysis.json", "w") as f:
    json.dump(
        {
            "model": MODEL,
            "pipeline": "local_llm_plus_deterministic_validation",
            "variants": results
        },
        f,
        indent=2
    )

print("\nSaved validated analysis to llm_analysis.json")
